[package]
edition = "2021"
name = "mcgrab-rs"
version = "0.1.0"
[dependencies]
futures = "0.3.19"
reqwest = "0.11.8"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "*"
tokio = { version = "1.15.0", features = ["full"] }
